"""
填充G-code生成模块
生成逐行扫描填充路径（根据点是否在轮廓内控制Z轴升降）
只在边界处改变Z轴，中间区域一次性走完
使用精确几何计算
"""

import cv2
import numpy as np


class FillGenerator:
    """UV扫描填充生成器"""

    def __init__(self, feed_rate=1000):
        self.feed_rate = feed_rate

    def _get_contours_bounds(self, contours):
        """获取轮廓边界"""
        all_points = [point[0] for contour in contours for point in contour]
        if not all_points:
            return 0, 0, 0, 0
        min_x = min(p[0] for p in all_points)
        max_x = max(p[0] for p in all_points)
        min_y = min(p[1] for p in all_points)
        max_y = max(p[1] for p in all_points)
        return min_x, max_x, min_y, max_y

    def _find_vertical_intersections(self, fixed_x, contours):
        """
        计算垂直线 X=fixed_x 与所有轮廓边段的精确交点

        Args:
            fixed_x: 固定的X坐标
            contours: OpenCV格式的轮廓列表

        Returns:
            list: 交点的Y坐标列表（已排序）
        """
        intersections = []

        for contour in contours:
            n = len(contour)
            for i in range(n):
                p1 = contour[i][0]
                p2 = contour[(i + 1) % n][0]

                x1, y1 = p1
                x2, y2 = p2

                # 检查边段是否与垂直线 X=fixed_x 相交
                # 边段必须跨越 fixed_x（即一个端点在左，一个在右，或端点恰好在线上）
                if (x1 <= fixed_x <= x2) or (x2 <= fixed_x <= x1):
                    # 避免除零（垂直边段）
                    if abs(x2 - x1) < 0.0001:
                        continue

                    # 计算交点的Y坐标（精确值）
                    y = y1 + (fixed_x - x1) * (y2 - y1) / (x2 - x1)
                    intersections.append(y)

        # 排序所有交点
        return sorted(intersections)

    def generate(self, contours, fill_interval, y_offset, z_depth,
                 image_width=0, image_height=0,
                 target_width=0, target_height=0, swap_xz=False):
        """
        生成逐行扫描填充G代码

        Args:
            contours: OpenCV格式的轮廓列表
            fill_interval: X轴行间隔(mm)，每行之间的X距离
            y_offset: Y轴偏移量(mm)，填充时的Y坐标 = 提取边时的Y坐标 + y_offset
            z_depth: Z轴切割深度(mm)，负值表示下探（如-2mm）
            image_width: 图像宽度(像素)
            image_height: 图像高度(像素)
            target_width: 目标宽度(mm)
            target_height: 目标高度(mm)
            swap_xz: 是否交换X轴和Z轴（X→Z, Y→Y, Z→X）

        Returns:
            str: G代码字符串
        """
        gcode_lines = []

        use_auto_scale = target_width > 0 and target_height > 0

        # 获取轮廓边界
        min_x, max_x, min_y, max_y = self._get_contours_bounds(contours)
        orig_width = max_x - min_x if max_x > min_x else 1
        orig_height = max_y - min_y if max_y > min_y else 1

        # 计算缩放和偏移
        if use_auto_scale:
            scale_x = target_width / orig_width if orig_width > 0 else 1
            scale_y = target_height / orig_height if orig_height > 0 else 1
            scale = min(scale_x, scale_y)

            scaled_width = orig_width * scale
            scaled_height = orig_height * scale

            offset_x = (target_width - scaled_width) / 2 - min_x * scale
            offset_y = (target_height - scaled_height) / 2 - min_y * scale
        else:
            scale = 1.0
            offset_x = 0
            offset_y = 0

        # Z轴安全高度（抬起位置）
        safe_z = 5.0

        # 转换间隔为像素单位
        x_interval_pixels = fill_interval / scale if scale > 0 else fill_interval
        y_offset_pixels = y_offset / scale if scale > 0 else y_offset

        # 扩展边界，确保扫描覆盖整个轮廓
        scan_min_x = min_x - x_interval_pixels
        scan_max_x = max_x + x_interval_pixels

        # Y轴偏移后的扫描范围
        scan_min_y = min_y
        scan_max_y = max_y

        # G代码头部
        gcode_lines.append("; AIpathCut Fill G-code")
        gcode_lines.append(f"; Generated by AIpathCut - Segment-based Scan Fill")
        gcode_lines.append(f"; X轴行间隔: {fill_interval} mm")
        gcode_lines.append(f"; Y轴偏移: {y_offset} mm")
        gcode_lines.append(f"; Z轴切割深度: {z_depth} mm")
        gcode_lines.append(f"; Z轴安全高度: {safe_z} mm")
        if swap_xz:
            gcode_lines.append("; XZ轴交换模式: X→Z, Y→Y, Z→X")
        if use_auto_scale:
            gcode_lines.append(f"; 加工区域: {target_width} x {target_height} mm")
            gcode_lines.append(f"; 等比缩放: {scale:.4f}")
        gcode_lines.append(f"; Feed rate: {self.feed_rate} mm/min")
        gcode_lines.append("; ---")
        gcode_lines.append("G21 ; Set units to millimeters")
        gcode_lines.append("G90 ; Absolute positioning")
        gcode_lines.append(f"G1 F{self.feed_rate} ; Set feed rate")

        # 先移动到起始位置并抬起
        start_x = scan_min_x * scale + offset_x
        start_y = (scan_min_y + y_offset_pixels) * scale + offset_y if use_auto_scale else scan_min_y + y_offset_pixels

        if swap_xz:
            gcode_lines.append(f"G0 X{safe_z:.3f} Y{start_y:.3f} Z{start_x:.3f} ; Safe height, move to start")
        else:
            gcode_lines.append(f"G0 Z{safe_z:.3f} ; Safe height")
            gcode_lines.append(f"G0 X{start_x:.3f} Y{start_y:.3f} ; Move to start")
        gcode_lines.append("")

        # 逐行扫描：固定X，找出垂直线与轮廓的精确交点
        x = scan_min_x
        first_segment = True

        while x <= scan_max_x:
            # 在当前X位置，找出与轮廓的所有交点
            intersections = self._find_vertical_intersections(x, contours)

            # 转换X坐标到输出坐标
            out_x = x * scale + offset_x

            # 配对交点生成线段
            # 偶数索引是入口，奇数索引是出口
            for i in range(0, len(intersections) - 1, 2):
                if i + 1 >= len(intersections):
                    break

                y_entry = intersections[i]      # 进入轮廓的Y
                y_exit = intersections[i + 1]   # 离开轮廓的Y

                # 转换Y坐标到输出坐标（应用偏移）
                out_y_entry = ((max_y - y_entry) * scale + offset_y + y_offset) if use_auto_scale else (image_height - y_entry + y_offset_pixels) if image_height > 0 else y_entry + y_offset_pixels
                out_y_exit = ((max_y - y_exit) * scale + offset_y + y_offset) if use_auto_scale else (image_height - y_exit + y_offset_pixels) if image_height > 0 else y_exit + y_offset_pixels

                # 进入轮廓：先抬起移动到入口，然后下刀
                if swap_xz:
                    gcode_lines.append(f"G0 X{safe_z:.3f} Y{out_y_entry:.3f} Z{out_x:.3f} ; Move to entry")
                    gcode_lines.append(f"G1 X{z_depth:.3f} Y{out_y_entry:.3f} Z{out_x:.3f} ; Plunge")
                else:
                    gcode_lines.append(f"G0 X{out_x:.3f} Y{out_y_entry:.3f} Z{safe_z:.3f} ; Move to entry")
                    gcode_lines.append(f"G1 X{out_x:.3f} Y{out_y_entry:.3f} Z{z_depth:.3f} ; Plunge")

                # 在轮廓内切割到出口
                if swap_xz:
                    gcode_lines.append(f"G1 X{z_depth:.3f} Y{out_y_exit:.3f} Z{out_x:.3f} ; Cut to exit")
                else:
                    gcode_lines.append(f"G1 X{out_x:.3f} Y{out_y_exit:.3f} Z{z_depth:.3f} ; Cut to exit")

                first_segment = False

            x += x_interval_pixels

        # 填充完成后抬起
        gcode_lines.append("")
        if swap_xz:
            gcode_lines.append(f"G0 X{safe_z:.3f} ; Retract to safe height (swap mode)")
        else:
            gcode_lines.append(f"G0 Z{safe_z:.3f} ; Retract to safe height")

        gcode_lines.append("")
        gcode_lines.append("; ---")
        gcode_lines.append("M30 ; End of program")

        return "\n".join(gcode_lines)

    def save_to_file(self, contours, filepath, fill_interval, y_offset, z_depth,
                     image_width=0, image_height=0,
                     target_width=0, target_height=0, swap_xz=False):
        """生成并保存填充G代码"""
        gcode = self.generate(contours, fill_interval, y_offset, z_depth,
                             image_width, image_height,
                             target_width, target_height, swap_xz)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(gcode)
        return True
