"""
G代码生成模块
将轮廓数据转换为G代码格式，支持自动缩放到指定尺寸
支持XZ轴交换（X→Z, Y→Y, Z→X）
"""


class GCodeGenerator:
    """G代码生成器"""

    def __init__(self, feed_rate=1000):
        """
        初始化G代码生成器

        Args:
            feed_rate: 进给速度 (mm/min)
        """
        self.feed_rate = feed_rate

    def _get_contours_bounds(self, contours):
        """
        获取所有轮廓的边界框

        Args:
            contours: OpenCV格式的轮廓列表

        Returns:
            tuple: (min_x, max_x, min_y, max_y)
        """
        all_points = [point[0] for contour in contours for point in contour]
        if not all_points:
            return 0, 0, 0, 0
        min_x = min(p[0] for p in all_points)
        max_x = max(p[0] for p in all_points)
        min_y = min(p[1] for p in all_points)
        max_y = max(p[1] for p in all_points)
        return min_x, max_x, min_y, max_y

    def _calculate_scale_and_offset(self, contours, target_width, target_height):
        """
        计算缩放比例和居中偏移（等比例缩放）

        Args:
            contours: OpenCV格式的轮廓列表
            target_width: 加工区域宽度(mm) - X轴方向，左右
            target_height: 加工区域高度(mm) - Y轴方向，上下

        Returns:
            tuple: (scale, offset_x, offset_y)

        说明：
            - 等比例缩放：保持原图长宽比不变形
            - 取较小的缩放比例确保图案完全放入加工区域
            - 图案在加工区域内居中
        """
        min_x, max_x, min_y, max_y = self._get_contours_bounds(contours)
        orig_width = max_x - min_x
        orig_height = max_y - min_y

        # 避免除零错误
        if orig_width == 0:
            orig_width = 1
        if orig_height == 0:
            orig_height = 1

        # 计算缩放比例（等比例：保持原图长宽比，使用较小的比例确保完全适配）
        scale_x = target_width / orig_width
        scale_y = target_height / orig_height
        scale = min(scale_x, scale_y)  # 等比例缩放，不变形

        # 计算缩放后的实际尺寸
        scaled_width = orig_width * scale
        scaled_height = orig_height * scale

        # 计算居中偏移（图案在加工区域内居中）
        offset_x = (target_width - scaled_width) / 2 - min_x * scale
        offset_y = (target_height - scaled_height) / 2 - min_y * scale

        return scale, offset_x, offset_y

    def generate(self, contours, image_width=0, image_height=0,
                 target_width=0, target_height=0, swap_xz=False):
        """
        生成G代码

        Args:
            contours: OpenCV格式的轮廓列表
            image_width: 图像宽度(像素)
            image_height: 图像高度(像素)
            target_width: 目标宽度(mm)，为0时使用原始比例(1像素=1毫米)
            target_height: 目标高度(mm)，为0时使用原始比例
            swap_xz: 是否交换X轴和Z轴（X→Z, Y→Y, Z→X）

        Returns:
            str: G代码字符串
        """
        gcode_lines = []

        # 判断是否使用自动缩放
        use_auto_scale = target_width > 0 and target_height > 0

        if use_auto_scale:
            # 自动缩放模式：计算缩放比例和偏移
            scale, offset_x, offset_y = self._calculate_scale_and_offset(
                contours, target_width, target_height
            )
        else:
            # 原始模式：使用像素直接作为毫米单位
            scale = 1.0
            offset_x = 0
            offset_y = 0

        # 获取轮廓边界（用于注释）
        min_x, max_x, min_y, max_y = self._get_contours_bounds(contours)
        orig_width = max_x - min_x if max_x > min_x else 0
        orig_height = max_y - min_y if max_y > min_y else 0

        # G代码头部
        gcode_lines.append("; AIpathCut G-code")
        gcode_lines.append(f"; Generated by AIpathCut")

        if use_auto_scale:
            # 计算实际缩放后的尺寸
            scaled_width = orig_width * scale
            scaled_height = orig_height * scale
            gcode_lines.append(f"; 原图轮廓: {orig_width:.1f} x {orig_height:.1f} 像素")
            gcode_lines.append(f"; 加工区域: {target_width} x {target_height} mm")
            gcode_lines.append(f"; 等比缩放: {scale:.4f} (保持长宽比)")
            gcode_lines.append(f"; 实际尺寸: {scaled_width:.1f} x {scaled_height:.1f} mm")
            gcode_lines.append(f"; 图案在加工区域内居中")
        else:
            gcode_lines.append(f"; Original image size: {image_width} x {image_height} pixels")
            gcode_lines.append(f"; Output size: {image_width} x {image_height} mm (1:1)")

        if swap_xz:
            gcode_lines.append("; XZ轴交换模式: X→Z, Y→Y, Z→X")
        gcode_lines.append(f"; Feed rate: {self.feed_rate} mm/min")
        gcode_lines.append("; ---")
        gcode_lines.append("G21 ; Set units to millimeters")
        gcode_lines.append("G90 ; Absolute positioning")
        gcode_lines.append(f"G1 F{self.feed_rate} ; Set feed rate")
        gcode_lines.append("")

        # 为每个轮廓生成路径
        for idx, contour in enumerate(contours):
            if len(contour) < 2:
                continue

            gcode_lines.append(f"; Contour {idx + 1}")

            # 转换第一个点（起点）
            start = contour[0][0]
            if use_auto_scale:
                # 自动缩放模式：应用缩放和偏移，Y轴翻转（图像坐标向下，G-code坐标向上）
                x = start[0] * scale + offset_x
                y = (max_y - start[1]) * scale + offset_y
            else:
                # 原始模式：直接使用像素值
                x = start[0]
                y = (image_height - start[1]) if image_height > 0 else start[1]

            if swap_xz:
                # XZ交换：X→Z, Y→Y, Z→X
                gcode_lines.append(f"G0 Y{y:.3f} Z{x:.3f} ; Move to start")
            else:
                gcode_lines.append(f"G0 X{x:.3f} Y{y:.3f} ; Move to start")

            # 生成路径点
            for point in contour[1:]:
                if use_auto_scale:
                    px = point[0][0] * scale + offset_x
                    py = (max_y - point[0][1]) * scale + offset_y
                else:
                    px = point[0][0]
                    py = (image_height - point[0][1]) if image_height > 0 else point[0][1]

                if swap_xz:
                    # XZ交换：X→Z, Y→Y, Z→X
                    gcode_lines.append(f"G1 Y{py:.3f} Z{px:.3f}")
                else:
                    gcode_lines.append(f"G1 X{px:.3f} Y{py:.3f}")

            # 闭合路径
            if swap_xz:
                gcode_lines.append(f"G1 Y{y:.3f} Z{x:.3f} ; Close contour")
            else:
                gcode_lines.append(f"G1 X{x:.3f} Y{y:.3f} ; Close contour")
            gcode_lines.append("")

        # G代码尾部
        gcode_lines.append("; ---")
        gcode_lines.append("M30 ; End of program")

        return "\n".join(gcode_lines)

    def save_to_file(self, contours, filepath, image_width=0, image_height=0,
                     target_width=0, target_height=0, swap_xz=False):
        """
        生成G代码并保存到文件

        Args:
            contours: OpenCV格式的轮廓列表
            filepath: 输出文件路径
            image_width: 图像宽度(像素)
            image_height: 图像高度(像素)
            target_width: 目标宽度(mm)
            target_height: 目标高度(mm)
            swap_xz: 是否交换X轴和Z轴（X→Z, Y→Y, Z→X）

        Returns:
            bool: 是否保存成功
        """
        try:
            gcode = self.generate(contours, image_width, image_height,
                                 target_width, target_height, swap_xz)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(gcode)
            return True
        except Exception as e:
            print(f"Error saving G-code: {e}")
            return False
